version: '2'
services:
 mysql:
  image: mysql
  restart: always
  ports:
   - "13306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=hypha
   - MYSQL_USER=hypha
   - MYSQL_PASSWORD=hypha
   - MYSQL_DATABASE=hypha


 hypha:
  # image:chriamue/hyphadocker
  build: .
  hostname: hypha
  restart: always
  ports:
   - "8080:80"

 hypha1:
  build: .
  hostname: hypha1
  restart: always
  ports:
   - "8081:80"
